### ISSUE TITLE
Having trouble to start it

### ISSUE THREAD

**Issue by TheRealMrSteel** [Shyri/TouchMapper#1]
Hi, first of all this looks really promising and exactly what I am looking for.
I was reading the User guide and it mentioned the latest apk version could be found in the release tab, but its empty unfortunately. Is it still possible to use this great tool or did you stop the developments?

Any help is greatly appreciated!

**Comment by Shyri** [comment]
You are right! I completely forgot to upload the binary to releases. I just uploaded the apk you can find it on releases. I'm not working on this project anymore but you should still be able to use it.

Let me know if you have more issues

**Comment by TheRealMrSteel** [comment]
Thanks for the quick reply and the upload!
Still having some problems though... enabled java in the browser to start TouchMapperLauncher.
Pressing the: **Webstart: click to launch this app as webstart** results in error:
`ExitException: Unable to load resource:
%path%/touchmapperlauncher.jar`

Pressing more info gives:
`ExitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: file:/C:/Users/nljvsta/Documents/Apps/TouchMapper-master/TouchMapperLauncher-master/touchmapperlauncher.jar
	at sun.plugin2.applet.JNLP2Manager.downloadResources(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.prepareLaunchFile(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.loadJarFiles(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
Might be a high possibility I'm doing something wrong since I'm not super experienced in running apps this way. 

I also tried running the gradlew.bat in powershell because I thought this had to be run for some preparations this also results in an error:

`FAILURE: Build failed with an exception.
What went wrong:
A problem occurred configuring project :app.
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 2s
`

Again, it's likely that it's a problem on my end, but I think I'm still missing some instructions in the How to launch section. Any help is appreciated!

**Comment by S0und** [comment]
@Shyri will you upload TouchMapperLauncher to release? Right now it's empty, what's why we can't use TouchMapper. I managed to build the Launcher, but the TouchMapper is constantly crashing:

https://pastebin.com/n1J8J1kU


Probably this would not happen, if we could run the Laucher as you intended.

**Comment by TheRealMrSteel** [comment]
I think we are out of luck here @S0und, Shyri already said he is not working on the project anymore.

**Comment by Shyri** [comment]
Sorry guys, let me have a look I'll check everything is well documented and binaries are in place

**Comment by Shyri** [comment]
Ok guys I just uploaded TouchMapperLauncher binary for Mac only I don't have windows, if any of you could build it for Windows I'll add it to the release. I've also made some clarifications for the User Guide that might help.

@TheRealMrSteel about your issue, it seems like you have some Android Studio or SDK setup problems. Please try using the apk provided in releases so you don't have to compile the application.

@S0und that trace points to something not right with the json configuration file. Could you please share the json file contents?
